---
title: "Episode 3 - Understanding your data"
teaching: 10
exercises: 1
---

:::::::::::::::::::::::::::::::::::::: questions 

- How do you start to think critically about a dataset from a QA/QC perspective?

::::::::::::::::::::::::::::::::::::::::::::::::

::::::::::::::::::::::::::::::::::::: objectives

- Explain the importance of establishing a mental model of a dataset
- Define/differentiate the data types in a dataset
- Compile a set of potential validation parameters for a dataset

::::::::::::::::::::::::::::::::::::::::::::::::

## Understanding Your Data

Before you can QA/QC data you need to understand the dataset as a whole, how the components of the dataset relate to each other, and the data types contained in the data set 




::::::::::::::::::::::::::::::::::::: discussion

## Juneau Ice Fields Weather Station: How do you QA/QC?

Read over the readME file for The [Juneau Icefield Weather station data] (https://www.sciencebase.gov/catalog/item/5d5b13f9e4b01d82ce8ed3be). What quality control procedures do the authors employ for the different data types? Alone or with a partner, Think about types of data you commonly work with and create a list of checks you do or may employ for those data.

::::::::::::::::::::::::::::::::::::::::::::::::



::::::::::::::::::::::::::::::::::::: keypoints 

- It is important to understand the dataset you are trying to QA/QC
- QA/QC can start before you even look at the data
- Understanding data types is key to being able to properly QA/QC data

::::::::::::::::::::::::::::::::::::::::::::::::

[r-markdown]: https://rmarkdown.rstudio.com/
